version: "3"


services:
  onos:
    image: onosproject/onos:2.7-latest
    container_name: mon_onos
    ports:
      - "8181:8181"
      - "6640:6640"
      - "6653:6653"
      - "8101:8101"
      - "9876:9876"
