version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle' # pour reloader avec la commande curl -X POST http://localhost:9090/-/reload
    ports:
      - 9090:9090
        #    restart: unless-stopped
    volumes:
      - /opt/monitoring/etc/prometheus:/etc/prometheus
      - /opt/monitoring/data/prometheus/:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
     - 3000:3000
    volumes:
      - /opt/monitoring/data/grafana/:/var/lib/grafana
      - /opt/monitoring/etc/grafana/:/etc/grafana/provisioning/
    depends_on:
      - prometheus

